export const CONTACT_MOCK_DATA_1 = {
  active: false,
  additionalContactDetails: [],
  archivedOn: undefined,
  communicationPreferenceEmail: false,
  communicationPreferenceLetter: false,
  communicationPreferencePhone: false,
  communicationPreferenceSMS: false,
  created: '2016-12-06T10:07:56Z',
  dateOfBirth: '1988-05-19',
  email: 'cwilliamson47@rpsfiction.net',
  forename: 'Christopher',
  fromArchive: false,
  homePhone: '02471896',
  id: 'MLK16000071',
  identityCheck: 'pass',
  marketingConsent: 'notAsked',
  metadata: {
    secondaryAddress: {},
    declarationRisk: {
      declarationForm: 'urlDeclarationForm.png',
      reason: 'erw23r',
      riskAssessmentForm: 'urlRiskAssessmentForm.png',
      type: 'Simplified',
    },
    primaryAddress: {
      documentImage:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/MLK16000071-primary-address-id(2).png',
      documentType: 'Mortgage Statement or Mortgage Redemption Statement',
      month: '8',
      year: '1',
    },
  },
  mobilePhone: '07110660399',
  modified: '2022-03-09T06:38:00Z',
  negotiatorIds: ['CLD'],
  officeIds: ['MLK'],
  primaryAddress: {
    buildingName: 'qwqd',
    buildingNumber: '3',
    countryId: 'GB',
    line1: 'Chichester Way',
    line2: 'Watford',
    line3: 'Hertfordshire',
    line4: 'qeq',
    postcode: 'WD25 9TY',
    type: 'primary',
  },
  secondaryAddress: undefined,
  source: { id: 'SRC61', type: 'source' },
  surname: 'Williamson',
  title: 'Mr',
  workAddress: undefined,
  workPhone: '028233444',
  _eTag: '"40FCC8984F885A89EDC06E8A223014E1"',
  _embedded: undefined,
  _links: {
    documents: { href: '/documents/?associatedType=contact&associatedId=MLK16000071' },
    identityChecks: { href: '/identityChecks/?contactId=MLK16000071' },
    negotiators: { href: '/negotiators/?id=CLD' },
    offices: { href: '/offices/?id=MLK' },
    relationships: { href: '/contacts/MLK16000071/relationships' },
    self: { href: '/contacts/MLK16000071' },
    subscriptions: { href: '/contacts/MLK16000071/subscriptions' },
  },
}

export const CONTACT_MOCK_DATA_2 = {
  active: false,
  additionalContactDetails: [],
  archivedOn: undefined,
  communicationPreferenceEmail: false,
  communicationPreferenceLetter: false,
  communicationPreferencePhone: false,
  communicationPreferenceSMS: false,
  created: '2016-12-06T10:07:56Z',
  dateOfBirth: '2020-05-19',
  email: 'cwilliamson47@rpsfiction.net',
  forename: 'Christopher',
  fromArchive: false,
  homePhone: undefined,
  id: 'MLK16000071',
  identityCheck: 'pass',
  marketingConsent: 'notAsked',
  metadata: {
    secondaryAddress: {
      documentImage:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/MLK16000071-primary-address-id(2).png',
      documentType: 'Mortgage Statement or Mortgage Redemption Statement',
      month: '8',
      year: '1',
    },
    declarationRisk: {
      declarationForm:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/declaration-Simplified-erw23r.png',
      reason: '',
      riskAssessmentForm:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/riskAssessment-Simplified-erw23r.png',
      type: 'Simplified',
    },
    primaryAddress: {
      documentImage:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/MLK16000071-primary-address-id(2).png',
      documentType: 'Mortgage Statement or Mortgage Redemption Statement',
      month: '8',
      year: '1',
    },
  },
  mobilePhone: undefined,
  modified: '2022-03-09T06:38:00Z',
  negotiatorIds: ['CLD'],
  officeIds: ['MLK'],
  primaryAddress: {
    buildingName: 'Primary Address Building Name Test 2',
    buildingNumber: '3',
    countryId: 'GB',
    line1: '',
    line2: '',
    line3: '',
    line4: '',
    postcode: 'WD25 9TY',
    type: 'primary',
  },
  secondaryAddress: {
    buildingName: 'Secondary Address Building Name Test 2',
    buildingNumber: '3',
    countryId: 'GB',
    line1: 'Chichester Way',
    line2: 'Watford',
    line3: 'Hertfordshire',
    line4: 'qeq',
    postcode: 'WD25 9TY',
    type: 'secondary',
  },
  source: { id: 'SRC61', type: 'source' },
  surname: 'Williamson',
  title: 'Mr',
  workAddress: undefined,
  workPhone: '038233444abc',
  _eTag: '"40FCC8984F885A89EDC06E8A223014E1"',
  _embedded: undefined,
  _links: {
    documents: { href: '/documents/?associatedType=contact&associatedId=MLK16000071' },
    identityChecks: { href: '/identityChecks/?contactId=MLK16000071' },
    negotiators: { href: '/negotiators/?id=CLD' },
    offices: { href: '/offices/?id=MLK' },
    relationships: { href: '/contacts/MLK16000071/relationships' },
    self: { href: '/contacts/MLK16000071' },
    subscriptions: { href: '/contacts/MLK16000071/subscriptions' },
  },
}
